#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 CouchPlay Contributors
#
# Generate per-instance Sunshine configuration files.
# Each instance gets its own config directory with unique port and display settings.
#
# Usage: ./01-generate-sunshine-config.sh <instance_index> [base_port] [display_name]
#   instance_index: 0-based index of the streaming instance
#   base_port:      starting port (default: 47989)
#   display_name:   output_name value for display selection (default: empty = auto)
#
# Example:
#   ./01-generate-sunshine-config.sh 0 47989 0    # Instance 0, port 47989, display 0
#   ./01-generate-sunshine-config.sh 1 48020 1    # Instance 1, port 48020, display 1

set -euo pipefail

INSTANCE_INDEX="${1:?Usage: $0 <instance_index> [base_port] [display_name]}"
BASE_PORT="${2:-47989}"
DISPLAY_NAME="${3:-}"
PORT_OFFSET=$((INSTANCE_INDEX * 30))

# Each instance gets its own config directory
CONFIG_DIR="/tmp/couchplay-sunshine-${INSTANCE_INDEX}"
mkdir -p "${CONFIG_DIR}"

ACTUAL_PORT=$((BASE_PORT + PORT_OFFSET))

# Generate sunshine.conf (INI-style key=value)
cat > "${CONFIG_DIR}/sunshine.conf" << CONF
# Sunshine config for CouchPlay streaming instance ${INSTANCE_INDEX}
# Generated by spike/01-generate-sunshine-config.sh

# === Network ===
port = ${ACTUAL_PORT}
address_family = ipv4
origin_web_ui_allowed = pc

# === Display Capture ===
# output_name: numeric index of the display to capture
# For KMS/DRM: use the connector index logged at startup
# For Wayland (wlgrab): use the output index (0, 1, 2...)
# Leave empty for auto-detection (uses first/primary display)
$(if [ -n "${DISPLAY_NAME}" ]; then
    echo "output_name = ${DISPLAY_NAME}"
else
    echo "# output_name = 0"
fi)

# adapter_name: GPU device path for hardware encoding
# Common values: /dev/dri/renderD128 (first GPU), /dev/dri/renderD129 (second GPU)
# adapter_name = /dev/dri/renderD128

# === Video ===
# encoder: auto, nvenc, vaapi, vulkan
# encoder = auto

# === Audio ===
# sink: PulseAudio/PipeWire sink name for audio capture
# Leave empty for default sink
# sink = alsa_output.pci-0000_01_00.1.hdmi-stereo

# === Credentials ===
# Web UI credentials (for pairing)
username = couchplay
password = couchplay

# === File Paths ===
# Each instance uses its own state and apps files
file_apps = ${CONFIG_DIR}/apps.json
credentials_file = ${CONFIG_DIR}/credentials.json
log_file = ${CONFIG_DIR}/sunshine.log

# === Input ===
# gamepad: auto, xone, ds5, switch
gamepad = auto
controller = enabled
keyboard = enabled
mouse = enabled
CONF

# Generate minimal apps.json
cat > "${CONFIG_DIR}/apps.json" << 'APPS'
{
  "env": {},
  "apps": [
    {
      "name": "Desktop",
      "image-path": "desktop.png"
    }
  ]
}
APPS

echo "=== Generated Sunshine config for instance ${INSTANCE_INDEX} ==="
echo "Config dir:  ${CONFIG_DIR}"
echo "Config file: ${CONFIG_DIR}/sunshine.conf"
echo "Base port:   ${ACTUAL_PORT}"
echo "Web UI:      https://localhost:$((ACTUAL_PORT + 1))"
echo "Video:       UDP $((ACTUAL_PORT + 9))"
echo "Control:     UDP $((ACTUAL_PORT + 10))"
echo "Audio:       UDP $((ACTUAL_PORT + 11))"
echo "RTSP:        TCP $((ACTUAL_PORT + 21))"
echo ""
echo "To launch: sunshine ${CONFIG_DIR}/sunshine.conf"
echo ""
echo "=== Config contents ==="
cat "${CONFIG_DIR}/sunshine.conf"
